// AUTO-GENERATED by scripts/sync-blog-manifest.mjs
// Do not edit manually.

import post0 from "../../../content/blog/adu-construction-los-angeles-costs-permits-2026.md?raw";
import post1 from "../../../content/blog/altadena-fire-rebuild-permits-costs-2026.md?raw";
import post2 from "../../../content/blog/beverly-hills-bel-air-estate-construction.md?raw";
import post3 from "../../../content/blog/brentwood-luxury-home-modernization-cost-2026.md?raw";
import post4 from "../../../content/blog/building-luxury-estate-los-angeles-international-buyer.md?raw";
import post5 from "../../../content/blog/chapter-7a-wui-compliance-homeowner-guide.md?raw";
import post6 from "../../../content/blog/coastal-construction-santa-monica-malibu-codes.md?raw";
import post7 from "../../../content/blog/contractor-for-business-managers-family-offices-los-angeles.md?raw";
import post8 from "../../../content/blog/custom-home-brentwood-lots-permits-westside.md?raw";
import post9 from "../../../content/blog/custom-home-builders-bel-air-los-angeles.md?raw";
import post10 from "../../../content/blog/custom-home-builders-hidden-hills.md?raw";
import post11 from "../../../content/blog/design-build-vs-hiring-architect-separately.md?raw";
import post12 from "../../../content/blog/encino-sherman-oaks-studio-city-luxury-remodel.md?raw";
import post13 from "../../../content/blog/estate-managers-hiring-contractor-los-angeles.md?raw";
import post14 from "../../../content/blog/fire-insurance-gap-palisades-rebuild.md?raw";
import post15 from "../../../content/blog/fire-resistant-materials-construction-los-angeles-2026.md?raw";
import post16 from "../../../content/blog/hillside-home-construction-bel-air-hollywood-hills.md?raw";
import post17 from "../../../content/blog/home-additions-los-angeles-costs-permits-process.md?raw";
import post18 from "../../../content/blog/how-family-offices-evaluate-select-contractors-high-value-real-estate.md?raw";
import post19 from "../../../content/blog/how-long-custom-home-take-build-los-angeles-timeline.md?raw";
import post20 from "../../../content/blog/how-to-vet-fire-rebuild-contractor-la.md?raw";
import post21 from "../../../content/blog/luxury-home-automation-control4-crestron-savant.md?raw";
import post22 from "../../../content/blog/luxury-home-builders-beverly-hills.md?raw";
import post23 from "../../../content/blog/luxury-home-builders-calabasas.md?raw";
import post24 from "../../../content/blog/luxury-home-builders-malibu.md?raw";
import post25 from "../../../content/blog/luxury-home-builders-pacific-palisades.md?raw";
import post26 from "../../../content/blog/luxury-home-builders-platinum-triangle-bel-air-holmby-hills-beverly-hills.md?raw";
import post27 from "../../../content/blog/luxury-kitchen-primary-suite-remodel-los-angeles.md?raw";
import post28 from "../../../content/blog/outdoor-living-construction-los-angeles-estates.md?raw";
import post29 from "../../../content/blog/pacific-palisades-fire-rebuild-guide-2026.md?raw";
import post30 from "../../../content/blog/remote-construction-management-los-angeles-international-property-owners.md?raw";
import post31 from "../../../content/blog/santa-monica-hillside-construction-geotechnical.md?raw";
import post32 from "../../../content/blog/seismic-retrofitting-luxury-homes-los-angeles.md?raw";
import post33 from "../../../content/blog/teardown-rebuild-vs-whole-home-remodel-los-angeles.md?raw";

export const rawBlogPosts = [
  post0,
  post1,
  post2,
  post3,
  post4,
  post5,
  post6,
  post7,
  post8,
  post9,
  post10,
  post11,
  post12,
  post13,
  post14,
  post15,
  post16,
  post17,
  post18,
  post19,
  post20,
  post21,
  post22,
  post23,
  post24,
  post25,
  post26,
  post27,
  post28,
  post29,
  post30,
  post31,
  post32,
  post33,
];
