// AUTO-GENERATED by scripts/sync-blog-manifest.mjs
// Do not edit manually.

import post0 from "../../../content/blog/altadena-fire-rebuild-permits-costs-2026.md?raw";
import post1 from "../../../content/blog/brentwood-luxury-home-modernization-cost-2026.md?raw";
import post2 from "../../../content/blog/chapter-7a-wui-compliance-homeowner-guide.md?raw";
import post3 from "../../../content/blog/fire-insurance-gap-palisades-rebuild.md?raw";
import post4 from "../../../content/blog/how-to-vet-fire-rebuild-contractor-la.md?raw";
import post5 from "../../../content/blog/luxury-home-automation-control4-crestron-savant.md?raw";
import post6 from "../../../content/blog/pacific-palisades-fire-rebuild-guide-2026.md?raw";
import post7 from "../../../content/blog/santa-monica-hillside-construction-geotechnical.md?raw";

export const rawBlogPosts = [
  post0,
  post1,
  post2,
  post3,
  post4,
  post5,
  post6,
  post7,
];
